<?php

namespace CryptoCompress\WebService\Yahoo\Weather\ConditionCodes;

class German {
    public static function get($code, $text) {

#d($code, $text);
        #$t1 = self::conditions1($text);
        $t2 = self::conditions2($text);

        return $t2;
    }

    private static function conditions1($input) {
        if($input == "Light Rain") $data = "Leichter Regen";
        elseif($input == "Haze") $data = "Dunst";
        elseif($input == "Unknown Precipitation") $data = "Niederschlag";
        elseif($input == "Partly Cloudy") $data = "Teilweise bewölkt";
        elseif($input == "Cloudy")	 $data = "Bewölkt";
        elseif($input == "Mostly Cloudy") $data = "überwiegend bewölkt";
        elseif($input == "Blowing Snow") $data = "Schneetreiben";
        elseif($input == "Drizzle") $data = "Nieselregen";
        elseif($input == "Light Rain Shower") $data = "Leichter Regenschauer";
        elseif($input == "Sunny") $data = "Sonnig";
        elseif($input == "Fair") $data = "Heiter";
        elseif($input == "Light Drizzle") $data = "Leichter Nieselregen";
        elseif($input == "Wintry Mix") $data = "Winterlicher Mix";
        elseif($input == "Clear") $data = "Klar";
        elseif($input == "Light Snow") $data = "Leichter Schneefall";
        elseif($input == "Fog") $data = "Nebel";
        elseif($input == "Mist") $data = "Nebel";
        elseif($input == "Showers in the Vicinity") $data = "Regenfälle in der Nähe";
        elseif($input == "Light Rain/Windy") $data = "Leichter Regen/Windig";
        elseif($input == "Rain and Snow") $data = "Schneeregen";
        elseif($input == "Light Snow") $data = "Leichter Schneefall";
        elseif($input == "Snow") $data = "Schneefall";
        elseif($input == "Rain") $data = "Regen";
        elseif($input == "Mostly Clear") $data = "überwiegend Klar";
        elseif($input == "Foggy") $data = "neblig";
        elseif($input == "Freezing Drizzle") $data = "gefrierender Nieselregen";
        elseif($input == "Freezing Rain") $data = "gefrierender Regen";
        elseif($input == "Mostly sunny") $data = "überwiegend sonnig";
        elseif($input == "Light Rain/Freezing Rain") $data = "Leichter Regen/Gefrierender Regen";
        elseif($input == "Light Snow Shower") $data = "Leichter Schneeschauer";
        elseif($input == "Ice Crystals") $data = "Eiskristalle";
        elseif($input == "Thunder") $data = "Gewitter";
        elseif($input == "Heavy Thunderstorm") $data = "Schweres Gewitter";
        elseif($input == "Thunderstorm") $data = "Gewitter";
        elseif($input == "Heavy Rain") $data = "Starker Regen";
        elseif($input == "Light Rain with Thunder") $data = "Leichter Regen mit Gewitter";
        elseif($input == "Thunder in the Vicinity") $data = "Gewitter in der Umgebung";
        elseif($input == "Partly Cloudy/Windy") $data = "Teilweise bewölkt/windig";
        elseif($input == "Light Rain Shower/Windy") $data = "Leichter Regenschauer/windig";
        elseif($input == "Patches of Fog") $data = "Nebelfelder";
        elseif($input == "Rain Shower") $data = "Regenschauer";
        elseif($input == "Light Freezing Rain") $data = "Leichter gefrierender Regen";
        elseif($input == "Rain Shower/Windy") $data = "Regenschauer/Windig";
        elseif($input == "Mostly Cloudy/Windy") $data = "Meist wolkig/Windig";
        elseif($input == "Snow Shower") $data = "Schneeschauer";
        elseif($input == "Patches of Fog/Windy") $data = "Nebelfelder/Windig";
        elseif($input == "Shallow Fog") $data = "flacher Nebel";
        elseif($input == "Cloudy/Windy") $data = "Wolkig/Windig";
        elseif($input == "Light Snow/Fog") $data = "Leichter Schneefall/Nebel";
        elseif($input == "Heavy Rain Shower") $data = "Starker Regenschauer";
        elseif($input == "Light Rain Shower/Fog") $data = "Leichter Regenschauer/Nebel";
        elseif($input == "Rain/Windy") $data = "Regen/Windig";
        elseif($input == "Drizzle/Windy") $data = "Nieselregen/Windig";
        elseif($input == "Heavy Drizzle") $data = "starker Nieselregen";
        elseif($input == "Squalls") $data = "Böen";
        elseif($input == "Heavy Thunderstorm/Windy") $data = "Schweres Gewitter/Windig";
        elseif($input == "Snow Grains") $data = "Schneegriesel";
        elseif($input == "Partial Fog") $data = "teilweise Nebel";
        elseif($input == "Snow/Windy") $data = "Schnee/Windig";
        elseif($input == "Fair/Windy") $data = "Heiter/Windig";
        elseif($input == "Heavy Snow/Windy") $data = "Starker Schneefall/Windig";
        elseif($input == "Heavy Snow") $data = "Starker Schneefall";
        elseif($input == "Light Snow Shower/Fog") $data = "Leichter Schneeschauer/Nebel";
        elseif($input == "Heavy Snow Shower") $data = "Starker Schneeschauer";
        elseif($input == "Light Snow/Windy") $data = "Leichter Schneeschauer/Windig";
        elseif($input == "Drifting Snow/Windy") $data = "Schneetreiben/Windig";
        elseif($input == "Light Snow/Windy/Fog") $data = "Leichter Schneeschauer/Windig/Nebel";
        elseif($input == "Freezing Drizzle/Windy") $data = "Gefrierender Nieselregen/Windig";
        elseif($input == "Light Snow/Freezing Rain") $data = "Leichter Schneefall/Gefrierender Regen";
        elseif($input == "Light Sleet") $data = "Leichter Schneeregen";
        elseif($input == "Light Freezing Drizzle") $data = "Leichter gefrierender Nieselregen";
        elseif($input == "Light Snow Grains") $data = "Leichter Schneegriesel";
        elseif($input == "Clear/Windy") $data = "Klar/Windig";
        elseif($input == "Heavy Rain/Windy") $data = "Starker Regen/Windig";
        elseif($input == "Fog/Windy") $data = "Nebel/Windig";
        elseif($input == "Unknown") $data = "unbekannt";
        elseif($input == "Sunny/Windy") $data = "Sonnig/Windig";
        elseif($input == "Sleet and Freezing Rain") $data = "Schneeregen und gefrierender Regen";
        elseif($input == "Clear/Windy") $data = "Klar/Windig";
        elseif($input == "Thunderstorm/Windy") $data = "Gewitter/Windig";
        elseif($input == "Light Snow with Thunder") $data = "Leichter Schneefall mit Gewitter";
        elseif($input == "Light Rain/Fog") $data = "Leichter Regen/Nebel";
        elseif($input == "Light Snow/Windy/Fog") $data = "Leichter Schneefall/Windig/Nebel";
        elseif($input == "Sleet/Windy") $data = "Schneeregen/Windig";
        elseif($input == "Rain and Snow/Windy ") $data = "Regen und Schnee/Windig";
        elseif($input == "Fog/Windy") $data = "Nebel/Windig";
        elseif($input == "Rain and Snow/Windy") $data = "Regen und Schnee/Windig";
        elseif($input == "Light Freezing Rain/Fog") $data = "Leichter gefrierender Regen/Nebel";
        elseif($input == "Drifting Snow") $data = "Schneetreiben";
        else $data = $input;
        return $data;
    }

    private static function conditions2($input) {
        if($input == "AM Clouds/PM Sun") $data = "vormittags bewölkt/nachmittags sonnig";
        elseif($input == "AM Drizzle") $data = "vormittags Nieselregen";
        elseif($input == "AM Drizzle/Wind") $data = "vorm. Nieselregen/Wind";
        elseif($input == "AM Fog/PM Clouds") $data = "vormittags Nebel/nachmittags bewölkt";
        elseif($input == "AM Fog/PM Sun") $data = "vormittags Nebel, nachmittags sonnig";
        elseif($input == "AM Ice") $data = "vorm. Eis";
        elseif($input == "AM Light Rain") $data = "vormittags leichter Regen";
        elseif($input == "AM Light Rain/Wind") $data = "vorm. leichter Regen/Wind";
        elseif($input == "AM Light Snow") $data = "vormittags leichter Schneefall";
        elseif($input == "AM Rain") $data = "vormittags Regen";
        elseif($input == "AM Rain/Snow Showers") $data = "vorm. Regen-/Schneeschauer";
        elseif($input == "AM Rain/Snow") $data = "vormittags Regen/Schnee";
        elseif($input == "AM Rain/Snow/Wind") $data = "vorm. Regen/Schnee/Wind";
        elseif($input == "AM Rain/Wind") $data = "vorm. Regen/Wind";
        elseif($input == "AM Showers") $data = "vormittags Schauer";
        elseif($input == "AM Showers/Wind") $data = "vormittags Schauer/Wind";
        elseif($input == "AM Snow Showers") $data = "vormittags Schneeschauer";
        elseif($input == "AM Snow") $data = "vormittags Schnee";
        elseif($input == "AM Thundershowers") $data = "vorm. Gewitterschauer";
        elseif($input == "Blowing Snow") $data = "Schneetreiben";
        elseif($input == "Clear") $data = "Klar";
        elseif($input == "Clear/Windy") $data = "Klar/Windig";
        elseif($input == "Clouds Early/Clearing Late") $data = "früh Wolken/später klar";
        elseif($input == "Cloudy") $data = "Bewölkt";
        elseif($input == "Cloudy/Wind") $data = "Bewölkt/Wind";
        elseif($input == "Cloudy/Windy") $data = "Wolkig/Windig";
        elseif($input == "Drifting Snow") $data = "Schneetreiben";
        elseif($input == "Drifting Snow/Windy") $data = "Schneetreiben/Windig";
        elseif($input == "Drizzle Early") $data = "früh Nieselregen";
        elseif($input == "Drizzle Late") $data = "später Nieselregen";
        elseif($input == "Drizzle") $data = "Nieselregen";
        elseif($input == "Drizzle/Fog") $data = "Nieselregen/Nebel";
        elseif($input == "Drizzle/Wind") $data = "Nieselregen/Wind";
        elseif($input == "Drizzle/Windy") $data = "Nieselregen/Windig";
        elseif($input == "Fair") $data = "Heiter";
        elseif($input == "Fair/Windy") $data = "Heiter/Windig";
        elseif($input == "Few Showers") $data = "vereinzelte Schauer";
        elseif($input == "Few Showers/Wind") $data = "vereinzelte Schauer/Wind";
        elseif($input == "Few Snow Showers") $data = "vereinzelt Schneeschauer";
        elseif($input == "Fog Early/Clouds Late") $data = "früh Nebel, später Wolken";
        elseif($input == "Fog Late") $data = "später neblig";
        elseif($input == "Fog") $data = "Nebel";
        elseif($input == "Fog/Windy") $data = "Nebel/Windig";
        elseif($input == "Foggy") $data = "neblig";
        elseif($input == "Freezing Drizzle") $data = "gefrierender Nieselregen";
        elseif($input == "Freezing Drizzle/Windy") $data = "gefrierender Nieselregen/Windig";
        elseif($input == "Freezing Rain") $data = "gefrierender Regen";
        elseif($input == "Haze") $data = "Dunst";
        elseif($input == "Heavy Drizzle") $data = "starker Nieselregen";
        elseif($input == "Heavy Rain Shower") $data = "Starker Regenschauer";
        elseif($input == "Heavy Rain") $data = "Starker Regen";
        elseif($input == "Heavy Rain/Wind") $data = "starker Regen/Wind";
        elseif($input == "Heavy Rain/Windy") $data = "Starker Regen/Windig";
        elseif($input == "Heavy Snow Shower") $data = "Starker Schneeschauer";
        elseif($input == "Heavy Snow") $data = "Starker Schneefall";
        elseif($input == "Heavy Snow/Wind") $data = "Starker Schneefall/Wind";
        elseif($input == "Heavy Thunderstorm") $data = "Schweres Gewitter";
        elseif($input == "Heavy Thunderstorm/Windy") $data = "Schweres Gewitter/Windig";
        elseif($input == "Ice Crystals") $data = "Eiskristalle";
        elseif($input == "Ice Late") $data = "später Eis";
        elseif($input == "Isolated T-storms") $data = "Vereinzelte Gewitter";
        elseif($input == "Isolated Thunderstorms") $data = "Vereinzelte Gewitter";
        elseif($input == "Light Drizzle") $data = "Leichter Nieselregen";
        elseif($input == "Light Freezing Drizzle") $data = "Leichter gefrierender Nieselregen";
        elseif($input == "Light Freezing Rain") $data = "Leichter gefrierender Regen";
        elseif($input == "Light Freezing Rain/Fog") $data = "Leichter gefrierender Regen/Nebel";
        elseif($input == "Light Rain Early") $data = "anfangs leichter Regen";
        elseif($input == "Light Rain") $data = "Leichter Regen";
        elseif($input == "Light Rain Late") $data = "später leichter Regen";
        elseif($input == "Light Rain Shower") $data = "Leichter Regenschauer";
        elseif($input == "Light Rain Shower/Fog") $data = "Leichter Regenschauer/Nebel";
        elseif($input == "Light Rain Shower/Windy") $data = "Leichter Regenschauer/windig";
        elseif($input == "Light Rain with Thunder") $data = "Leichter Regen mit Gewitter";
        elseif($input == "Light Rain/Fog") $data = "Leichter Regen/Nebel";
        elseif($input == "Light Rain/Freezing Rain") $data = "Leichter Regen/Gefrierender Regen";
        elseif($input == "Light Rain/Wind Early") $data = "früh leichter Regen/Wind";
        elseif($input == "Light Rain/Wind Late") $data = "später leichter Regen/Wind";
        elseif($input == "Light Rain/Wind") $data = "leichter Regen/Wind";
        elseif($input == "Light Rain/Windy") $data = "Leichter Regen/Windig";
        elseif($input == "Light Sleet") $data = "Leichter Schneeregen";
        elseif($input == "Light Snow Early") $data = "früher leichter Schneefall";
        elseif($input == "Light Snow Grains") $data = "Leichter Schneegriesel";
        elseif($input == "Light Snow Late") $data = "später leichter Schneefall";
        elseif($input == "Light Snow Shower") $data = "Leichter Schneeschauer";
        elseif($input == "Light Snow Shower/Fog") $data = "Leichter Schneeschauer/Nebel";
        elseif($input == "Light Snow with Thunder") $data = "Leichter Schneefall mit Gewitter";
        elseif($input == "Light Snow") $data = "Leichter Schneefall";
        elseif($input == "Light Snow/Fog") $data = "Leichter Schneefall/Nebel";
        elseif($input == "Light Snow/Freezing Rain") $data = "Leichter Schneefall/Gefrierender Regen";
        elseif($input == "Light Snow/Wind") $data = "Leichter Schneefall/Wind";
        elseif($input == "Light Snow/Windy") $data = "Leichter Schneeschauer/Windig";
        elseif($input == "Light Snow/Windy/Fog") $data = "Leichter Schneefall/Windig/Nebel";
        elseif($input == "Mist") $data = "Nebel";
        elseif($input == "Mostly Clear") $data = "überwiegend Klar";
        elseif($input == "Mostly Cloudy") $data = "Überwiegend bewölkt";
        elseif($input == "Mostly Cloudy/Wind") $data = "meist bewölkt/Wind";
        elseif($input == "Mostly sunny") $data = "Überwiegend sonnig";
        elseif($input == "Partial Fog") $data = "teilweise Nebel";
        elseif($input == "Partly Cloudy") $data = "Teilweise bewölkt";
        elseif($input == "Partly Cloudy/Wind") $data = "teilweise bewölkt/Wind";
        elseif($input == "Patches of Fog") $data = "Nebelfelder";
        elseif($input == "Patches of Fog/Windy") $data = "Nebelfelder/Windig";
        elseif($input == "PM Drizzle") $data = "nachm. Nieselregen";
        elseif($input == "PM Fog") $data = "nachmittags Nebel";
        elseif($input == "PM Light Snow") $data = "nachmittags leichter Schneefall";
        elseif($input == "PM Light Rain") $data = "nachmittags leichter Regen";
        elseif($input == "PM Light Rain/Wind") $data = "nachm. leichter Regen/Wind";
        elseif($input == "PM Light Snow/Wind") $data = "nachm. leichter Schneefall/Wind";
        elseif($input == "PM Rain") $data = "nachmittags Regen";
        elseif($input == "PM Rain/Snow Showers") $data = "nachmittags Regen/Schneeschauer";
        elseif($input == "PM Rain/Snow") $data = "nachmittags Regen/Schnee";
        elseif($input == "PM Rain/Wind") $data = "nachm. Regen/Wind";
        elseif($input == "PM Showers") $data = "nachmittags Schauer";
        elseif($input == "PM Showers/Wind") $data = "nachmittags Schauer/Wind";
        elseif($input == "PM Snow Showers") $data = "nachmittags Schneeschauer";
        elseif($input == "PM Snow Showers/Wind") $data = "nachm. Schneeschauer/Wind";
        elseif($input == "PM Snow") $data = "nachm. Schnee";
        elseif($input == "PM T-storms") $data = "nachmittags Gewitter";
        elseif($input == "PM Thundershowers") $data = "nachmittags Gewitterschauer";
        elseif($input == "PM Thunderstorms") $data = "nachm. Gewitter";
        elseif($input == "Rain and Snow") $data = "Schneeregen";
        elseif($input == "Rain and Snow/Windy") $data = "Regen und Schnee/Windig";
        elseif($input == "Rain/Snow Showers/Wind") $data = "Regen/Schneeschauer/Wind";
        elseif($input == "Rain Early") $data = "früh Regen";
        elseif($input == "Rain Late") $data = "später Regen";
        elseif($input == "Rain Shower") $data = "Regenschauer";
        elseif($input == "Rain Shower/Windy") $data = "Regenschauer/Windig";
        elseif($input == "Rain to Snow") $data = "Regen, in Schnee übergehend";
        elseif($input == "Rain") $data = "Regen";
        elseif($input == "Rain/Snow Early") $data = "früh Regen/Schnee";
        elseif($input == "Rain/Snow Late") $data = "später Regen/Schnee";
        elseif($input == "Rain/Snow Showers Early") $data = "früh Regen-/Schneeschauer";
        elseif($input == "Rain/Snow Showers Late") $data = "später Regen-/Schneeschnauer";
        elseif($input == "Rain/Snow Showers") $data = "Regen/Schneeschauer";
        elseif($input == "Rain/Snow") $data = "Regen/Schnee";
        elseif($input == "Rain/Snow/Wind") $data = "Regen/Schnee/Wind";
        elseif($input == "Rain/Thunder") $data = "Regen/Gewitter";
        elseif($input == "Rain/Wind Early") $data = "früh Regen/Wind";
        elseif($input == "Rain/Wind Late") $data = "später Regen/Wind";
        elseif($input == "Rain/Wind") $data = "Regen/Wind";
        elseif($input == "Rain/Windy") $data = "Regen/Windig";
        elseif($input == "Scattered Showers") $data = "vereinzelte Schauer";
        elseif($input == "Scattered Showers/Wind") $data = "vereinzelte Schauer/Wind";
        elseif($input == "Scattered Snow Showers") $data = "vereinzelte Schneeschauer";
        elseif($input == "Scattered Snow Showers/Wind") $data = "vereinzelte Schneeschauer/Wind";
        elseif($input == "Scattered T-storms") $data = "vereinzelte Gewitter";
        elseif($input == "Scattered Thunderstorms") $data = "vereinzelte Gewitter";
        elseif($input == "Shallow Fog") $data = "flacher Nebel";
        elseif($input == "Showers") $data = "Schauer";
        elseif($input == "Showers Early") $data = "früh Schauer";
        elseif($input == "Showers Late") $data = "später Schauer";
        elseif($input == "Showers in the Vicinity") $data = "Regenfälle in der Nähe";
        elseif($input == "Showers/Wind") $data = "Schauer/Wind";
        elseif($input == "Sleet and Freezing Rain") $data = "Schneeregen und gefrierender Regen";
        elseif($input == "Sleet/Windy") $data = "Schneeregen/Windig";
        elseif($input == "Snow Grains") $data = "Schneegriesel";
        elseif($input == "Snow Late") $data = "später Schnee";
        elseif($input == "Snow Shower") $data = "Schneeschauer";
        elseif($input == "Snow Showers Early") $data = "früh Schneeschauer";
        elseif($input == "Snow Showers Late") $data = "später Schneeschauer";
        elseif($input == "Snow Showers") $data = "Schneeschauer";
        elseif($input == "Snow Showers/Wind") $data = "Schneeschauer/Wind";
        elseif($input == "Snow to Rain") $data = "Schneeregen";
        elseif($input == "Snow") $data = "Schneefall";
        elseif($input == "Snow/Wind") $data = "Schneefall/Wind";
        elseif($input == "Snow/Windy") $data = "Schnee/Windig";
        elseif($input == "Squalls") $data = "Böen";
        elseif($input == "Sunny") $data = "Sonnig";
        elseif($input == "Sunny/Wind") $data = "Sonnig/Wind";
        elseif($input == "Sunny/Windy") $data = "Sonnig/Windig";
        elseif($input == "T-showers") $data = "Gewitterschauer";
        elseif($input == "Thunder in the Vicinity") $data = "Gewitter in der Umgebung";
        elseif($input == "Thunder") $data = "Gewitter";
        elseif($input == "Thundershowers Early") $data = "früh Gewitterschauer";
        elseif($input == "Thundershowers") $data = "Gewitterschauer";
        elseif($input == "Thunderstorm") $data = "Gewitter";
        elseif($input == "Thunderstorm/Windy") $data = "Gewitter/Windig";
        elseif($input == "Thunderstorms Early") $data = "früh Gewitter";
        elseif($input == "Thunderstorms Late") $data = "später Gewitter";
        elseif($input == "Thunderstorms") $data = "Gewitter";
        elseif($input == "Unknown Precipitation") $data = "Niederschlag";
        elseif($input == "Unknown") $data = "unbekannt";
        elseif($input == "Wintry Mix") $data = "Winterlicher Mix";
        else $data = $input;
        return $data;
    }
}